ALTER TABLE task_grants ADD COLUMN IF NOT EXISTS catalog_digest TEXT NOT NULL DEFAULT '';
ALTER TABLE task_grants ADD COLUMN IF NOT EXISTS datasource_id TEXT NOT NULL DEFAULT '';
ALTER TABLE task_grants ADD COLUMN IF NOT EXISTS schema_digest TEXT NOT NULL DEFAULT '';

ALTER TABLE query_records ADD COLUMN IF NOT EXISTS datasource_id TEXT NOT NULL DEFAULT '';
ALTER TABLE query_records ADD COLUMN IF NOT EXISTS schema_digest TEXT NOT NULL DEFAULT '';
