#!/bin/sh
# Generate a complete Compose .env for the offline deployment bundle.
#
# compose.yaml fails closed (${VAR:?}) without these values, so the bundle
# ships one generated set; the offline server never needs openssl. The file is
# written 0600 and must only travel inside the private bundle.
#
# usage: make-env.sh OUTPUT_FILE
set -eu

repo="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)"
output="${1:?usage: make-env.sh OUTPUT_FILE}"

command -v openssl >/dev/null 2>&1 || { echo "openssl is required" >&2; exit 1; }

secret() {
  openssl rand -base64 32 | tr -d '\n'
}

umask 077
tmp="$(mktemp "${output}.tmp-XXXXXX")"
trap 'rm -f "$tmp"' EXIT INT TERM

{
  echo "# Generated by offline/nas/make-env.sh on $(date -u +%FT%TZ)."
  echo "# Private deployment secrets for the offline bundle; never commit."
  echo "GATEWAY_DATA_KEY=$(secret)"
  echo "GATEWAY_DATA_KEY_ID=local-aes256-gcm-v1"
  "$repo/scripts/generate-ed25519-env.sh"
  echo "TASKBOUND_ALICE_TOKEN=$(secret)"
  echo "TASKBOUND_CAROL_TOKEN=$(secret)"
  echo "GATEWAY_ADMIN_TOKEN=$(secret)"
  echo "TASKGATE_FINAL_V5_CONCURRENCY_TOKEN=$(secret)"
  echo "MINIO_ROOT_USER=taskgate-minio-admin"
  echo "MINIO_ROOT_PASSWORD=$(secret)"
  echo "GATEWAY_OBJECT_STORE_ACCESS_KEY=taskgate-gateway"
  echo "GATEWAY_OBJECT_STORE_SECRET_KEY=$(secret)"
  echo "GATEWAY_DELIVERY_SIGNING_KEY=$(secret)"
  echo "OA_SERVICE_TOKEN=$(secret)"
  echo "OA_CALLBACK_SECRET=$(secret)"
  echo "OA_SESSION_SECRET=$(secret)"
  echo "OA_ALICE_PASSWORD=$(secret)"
  echo "OA_BOB_PASSWORD=$(secret)"
  echo "CONTROL_POSTGRES_ADMIN_PASSWORD=$(secret)"
  echo "CONTROL_DB_PASSWORD=$(secret)"
  echo "POSTGRES_PASSWORD=$(secret)"
  echo "GATEWAY_DB_PASSWORD=$(secret)"
} > "$tmp"

mv "$tmp" "$output"
trap - EXIT INT TERM
echo "wrote $output"
